before_script:
  - docker info

build_image:
  script:
    - docker build -t pyspark_testing_env docker/
    - docker run --rm -v $(pwd):/project pyspark_testing_env bash -c 'cd project && py3clean . && python -m pip install -r requirements.txt && nosetests'